### ISSUE TITLE
ADVANCED CRATE 1.20.2 

### ISSUE THREAD

**Issue by ProAlexYTB** [slvlr/PM2-Plugins#70]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?

**Versions:**
 - Server Version: Purpur-2088 1.20.2
 - Plugin Version: 3.9.24

**Describe the bug**
I moved from Paper 1.20.1 to Purpur 1.20.2 and i got the spam error skull

**To Reproduce**
When i start the server i got the error

**Expected behavior**

**Screenshots**

**Error / Logs**
https://pastebin.com/gPk8nf0M

**Config File**
Please post your config file to https://pastebin.com and provide your Pastebin URL.

**Crate File**
Please upload the crate files that you are having issues with to https://pastebin.com and provide your Pastebin URL.

**Comment by ProAlexYTB** [comment]
[19:40:06 WARN]: [AdvancedCrates] Plugin AdvancedCrates v3.9.24 generated an exception while executing task 1087176
java.lang.NoSuchFieldError: isSilent
        at me.PM2.HologramPackets.v1_20_R2.NMSHandler.getLightningPacket(NMSHandler.java:616) ~[AdvancedCrates.jar:?]
        at me.PM2.AdvancedCrates.animations.round.RoundAnimation.sendLightningPacket(RoundAnimation.java:1352) ~[AdvancedCrates.jar:?]
        at me.PM2.AdvancedCrates.animations.round.RoundAnimation$5.run(RoundAnimation.java:995) ~[AdvancedCrates.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2090]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2090]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by ProAlexYTB** [comment]
https://mclo.gs/SPnk1oA

**Comment by EmanYm** [comment]
To add to this issue, here are two latest logs.  One with AdvancedCrates activated and one without.
[no AdvancedCrates latest.log](https://github.com/slvlr/PM2-Plugins/files/13384608/no.AdvancedCrates.latest.log)
[with AdvancedCrates latest.log](https://github.com/slvlr/PM2-Plugins/files/13384609/with.AdvanccedCrates.latest.log)
And my current config folder:
[AdvancedCrates.zip](https://github.com/slvlr/PM2-Plugins/files/13384641/AdvancedCrates.zip)

The version of Purpur provided by my host
> This server is running Purpur version git-Purpur-2089 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: ea2835b on HEAD)

AC version
> [AdvancedCrates] Loading server plugin AdvancedCrates v3.9.26

Right around line 861 of the 'with ac' log starts:
> [21:35:39] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[21:35:39] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R2' loaded!
[21:35:39] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'AdvancedCrates' to create a bStats instance!
[21:35:39] [Server thread/WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).


Edit:
I just realised there is a debug option in the config.  I'll enable that and upload a new "with ac" latest in a moment


It doesn't appear to have given any more information than than we got without debug mode.
[with AdvancedCrates-debug latest.log](https://github.com/slvlr/PM2-Plugins/files/13384794/with.AdvancedCrates-debug.latest.log)

**Comment by ProAlexYTB** [comment]
I found one more bug, updated to 3.9.27

[03:37:41 WARN]: [AdvancedCrates] Plugin AdvancedCrates v3.9.27 generated an exception while executing task 60633
java.lang.NoSuchFieldError: isSilent
        at me.PM2.HologramPackets.v1_20_R2.NMSHandler.getLightningPacket(NMSHandler.java:620) ~[AdvancedCrates.jar:?]
        at me.PM2.AdvancedCrates.animations.round.RoundAnimation.sendLightningPacket(RoundAnimation.java:1352) ~[AdvancedCrates.jar:?]
        at me.PM2.AdvancedCrates.animations.round.RoundAnimation$5.run(RoundAnimation.java:995) ~[AdvancedCrates.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2090]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2090]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

i found on round animation he got duplicate item, instead of giving one diamond i got two, i check the prizes it says one

**Comment by ThePM2** [comment]
fixed
